### ISSUE TITLE
Sprockets 1.x v.s. 2.x

### ISSUE THREAD

**Issue by jlgeering** [mraaroncruz/guard-sprockets#1]
doesn't work with Sprockets v 2.0.0:

```
ERROR: Guard::Sprockets failed to achieve its <run_on_change>, exception was:
NameError: uninitialized constant Sprockets::Secretary
/.../gems/guard-sprockets-0.1.4/lib/guard/sprockets.rb:33:in `sprocketize'
/.../gems/guard-sprockets-0.1.4/lib/guard/sprockets.rb:22:in `run_on_change'
```

probably a simple fix, see https://github.com/sstephenson/sprockets/issues/187

**Comment by jlgeering** [comment]
and maybe this https://github.com/stevehodgkiss/guard-sprockets2

**Comment by mraaroncruz** [comment]
I'll do a complete rewrite.  The code was just thrown together in the first place.  It will be available next Tuesday, I don't have any time at the minute because I just had a kid last weekend :)  
or by any means, submit a patch.  
thanks,  
aaron

**Comment by mraaroncruz** [comment]
yeah, he actually has specs too.  If his works well, I might just let this one die.  No need for two in this space.

**Comment by mraaroncruz** [comment]
Just upgraded with a pull request from @kemazy
