### ISSUE TITLE
Any way to compile Coffeescript with "bare" option?

### ISSUE THREAD

**Issue by mattfordham** [mraaroncruz/guard-sprockets#10]
I am needing to compile my Coffeescript with the "bare" option where the compiled JS is not wrapped in a anonymous function. Is this possible?

**Comment by mraaroncruz** [comment]
Hi,
Sorry for the delay.
This will not be supported for reasons explained here http://stackoverflow.com/a/6099872/376680.
But if you need to, you should be able to add this to your code (or a fork of this project)  
`Tilt::CoffeeScriptTemplate.default_bare = true`  
Also, the more active/up to date version of this repo is at https://github.com/guard/guard-sprockets
Thanks,
Aaron
