### ISSUE TITLE
Specify output file

### ISSUE THREAD

**Issue by gsmaverick** [mraaroncruz/guard-sprockets#8]
Much like guard-uglify allows you to specify the name of the output file.  For instance I have the following guard:

```
guard 'sprockets', :destination => 'build', :asset_paths => ['Source/Sass'] do
  watch 'Source/Sass/application.scss'
end
```

I would like to specify an :output => 'build/application.css' to have the generated file be put at that location.

**Comment by mraaroncruz** [comment]
I don't think this makes sense in the context of sprockets. This should be taken care of in your manifest or application.js/css files. 
Check out the options on the [guard/guard-sprockets](https://github.com/guard/guard-sprockets#options) readme.
