### ISSUE TITLE
guard-sprockets requires execjs but this is not a specified dependency

### ISSUE THREAD

**Issue by kapowaz** [mraaroncruz/guard-sprockets#9]
When executing `guard init sprockets` through bundle exec, I was getting the following error:

```
$ bundle exec guard init
15:13:36 - ERROR - Could not load 'guard/sprockets' or '~/.guard/templates/sprockets' or find class Guard::Sprockets
```

In attempting to diagnose this, I ran `bundle console` then attempted to `require 'guard-sprockets'` from irb, and got this error:

```
LoadError: cannot load such file -- execjs
```

Adding this gem to my Gemfile and rebundling solved the issue, but execjs isn't listed as a dependency for guard-sprockets. Perhaps it should be?

**Comment by mraaroncruz** [comment]
Just added this to [guard/guard-sprockets](https://github.com/guard/guard-sprockets/commit/9cde5a9056ece150dedeb62c07c4068763feb73b) which is the active repo.
Sorry for the delay.
